# Generated by Django 2.2.5 on 2020-04-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_information_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='small_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.SmallClass'),
        ),
    ]
