# Generated by Django 2.2.5 on 2020-02-11 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sente', models.CharField(max_length=50)),
                ('gote', models.CharField(max_length=50)),
                ('result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('my_result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('large_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifu_app.LargeClass')),
            ],
        ),
        migrations.CreateModel(
            name='SmallClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('middle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifu_app.MiddleClass')),
            ],
        ),
        migrations.CreateModel(
            name='Kifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('te', models.CharField(max_length=20)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifu_app.Information')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='small_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifu_app.SmallClass'),
        ),
    ]
