# Generated by Django 2.2.5 on 2020-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_kifu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylist',
            name='game_id',
            field=models.CharField(max_length=48),
        ),
    ]
