# Generated by Django 2.2.5 on 2020-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_kifu', '0002_auto_20200319_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_sync', models.DateTimeField()),
            ],
        ),
    ]
