# Generated by Django 2.2.5 on 2020-03-25 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_kifu', '0003_latestsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylist',
            name='saved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
